### ISSUE TITLE
Feature: Allow interaction without initial download

### ISSUE THREAD

**Issue by vectorlit** [vectorlit/UnofficialGenconMobile#9]
Very targeted feature - when the app first opens (after an initial install), it requires the user to sit through a loading screen as it loads all the events. 

1. This feature request is to move the event loading screen into a compressed modal/small form that appears on each tab, so the user can see progress, but still interact with the app. 
2. The modal/small form should not interfere with tab switching or user intents. 
3. The search screen should notify the user that events are still being downloaded if they attempt to search before an initial download is completed.
4. The maps screen should notify the user that maps are still being downloaded if they attempt to view maps before an initial download is completed (it should warn that they may be out of date).

**Comment by garkenxian** [comment]
i'll take this one... im not a part of this project as a contributer so I cant assign myself to it.

**Comment by vectorlit** [comment]
awesome thanks! I can't add you as an assignee until the first code contribution. It seems that GitHub is looking into making a change to this but for now it'll wait until the first pull request.

**Comment by garkenxian** [comment]
https://github.com/vectorlit/UnofficialGenconMobile/pull/13

**Comment by vectorlit** [comment]
Completed and merged, follow-up changes in https://github.com/vectorlit/UnofficialGenconMobile/commit/45ca3623536d8b6325aa3f765185810b737a7b3f
